openapi: 3.0.0
info:
  version: 0.0.0
  title: API Consulto De Peliculas/Series
  description: Api para mi proyecto TFG de DAW usando OpenAPI

servers:
  - url: http://localhost:5000

paths:
  /comentarios:
    get:
      summary: Obtener todos los comentarios
      responses:
        '200':
          description: Lista de todos los comentarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userName:
                      type: string
                    text:
                      type: string

    post:
      summary: Crear un nuevo comentario
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string

      responses:
        '201':
          description: Comentario creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  userId:
                    type: string
                  text:
                    type: string

  /comentarios/{id}:
    put:
      summary: Actualizar un comentario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string

      responses:
        '200':
          description: Comentario actualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  userId:
                    type: string
                  text:
                    type: string

    delete:
      summary: Eliminar un comentario
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      responses:
        '204':
          description: Comentario eliminado

  /auth/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nameUser:
                  type: string
                email:
                  type: string
                password:
                  type: string

      responses:
        '200':
          description: Usuario registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /auth/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT